# Generated by Django 4.2.6 on 2023-10-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperaturedata',
            old_name='temperature',
            new_name='celsius',
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='fahrenheit',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='hic',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='hif',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
