# Generated by Django 4.2.6 on 2023-11-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardjango', '0002_rename_temperature_temperaturedata_celsius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperaturedata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='hic',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='hif',
        ),
        migrations.RemoveField(
            model_name='temperaturedata',
            name='time',
        ),
    ]
