# Generated by Django 4.2.6 on 2023-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardjango', '0003_remove_temperaturedata_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturedata',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
