# Generated by Django 4.2.6 on 2023-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardjango', '0004_temperaturedata_date_temperaturedata_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturedata',
            name='hic',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='temperaturedata',
            name='hif',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
